[cmdra]
target ansible_connection=cmdra ansible_cmdra_address=127.0.0.1:8443 ansible_cmdra_ca_cert=dev/certs/ca.crt ansible_cmdra_client_cert=dev/certs/client-a.crt ansible_cmdra_client_key=dev/certs/client-a.key
