[cmdagent]
target ansible_connection=cmdagent ansible_cmdagent_address=127.0.0.1:8443 ansible_cmdagent_ca_cert=certs/ca.crt ansible_cmdagent_client_cert=certs/client-a.crt ansible_cmdagent_client_key=certs/client-a.key
